# Site settings
title: a freewriting blog
email: jim@pulamusic.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog of freewriting, devised as an exercise in regular writing. There is no deeper meaning.
baseurl: "/jekyll-base/" # the subpath of your site, e.g. /blog/
url: "https://pulamusic.github.io/" # the base hostname & protocol for your site
github_username:  pulamusic
paginate: 10
paginate_path: "/blog/page:num/"
# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
